### ISSUE TITLE
Question: given it's locking primitive, can I use it for leader election?

### ISSUE THREAD

**Issue by didip** [buraksezer/olric#113]

**Comment by buraksezer** [comment]
Hi @didip 

Olric is an eventually consistent data store. In the context of CAP principle, Olric is an AP store. It means that in the case of partitioning, Olric remains available but it may returns inconsistent results to its clients. The locking primitive is a part of the distributed map implementation. I recommend the lock implementation to be used for efficiency purposes in general, instead of correctness.

Even so, I would like to hear more about your use case. Are you implementing a consensus algorithm?

**Comment by didip** [comment]
Many times when I am writing a web app, there's always some features that requires only 1 instance of it doing the job (a.k.a the leader).

Usually I solved this using etcd, I am just wondering if I can use olric for the same use-case.

**Comment by buraksezer** [comment]
I see. In Olric, every partition(and every key) has an owner and all write operations is only done by the owner. So lock/unlock operations on a key is only done by the partition owner. But distributed locking is complicated matter. See this: https://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html

By the way, Olric has a concept called "cluster coordinator". It's the oldest member of the cluster and acts like the leader node.
