### ISSUE TITLE
How to decode cluster events?

### ISSUE THREAD

**Issue by Tochemey** [buraksezer/olric#239]
there is an encode method for event but there is no decode method. Also events are sent as string. How do we parse cluster events since there is no decode method?
https://github.com/buraksezer/olric/blob/master/events/cluster_events.go#L39

**Comment by Tochemey** [comment]
from the code I can see cluster events are marshalled using some custom json encoding pattern. If that is the case I believe a json.Unmarshal should do the job.

**Comment by buraksezer** [comment]
As you can easily see, those events are encoded as JSON messages. I didn't prefer to use the standard encoder because the location of the fields was random. I wanted to locate all fields at the same location in every message. 

Messages are public structs. You can directly use them to decode cluster events.

A sample cluster event: 

```
{"timestamp":585199808000,"source":"127.0.0.1:3423","kind":"node-join-event","node_join":"127.0.0.1:3576"}
```

You can easily extract the event kind from the message, then you can decode it using the following type:

```go
type NodeJoinEvent struct {
	Kind      string `json:"kind"`
	Source    string `json:"source"`
	NodeJoin  string `json:"node_join"`
	Timestamp int64  `json:"timestamp"`
}
```

**Comment by Tochemey** [comment]
Thanks

**Comment by Tochemey** [comment]
@buraksezer https://github.com/buraksezer/olric/blob/master/internal/cluster/routingtable/events.go#L31 converting unix nano nack to time can be hard because of the nano second part.

**Comment by buraksezer** [comment]
You should handle this sort of thing in your application code. You can easily convert nanoseconds to milliseconds. This is not a bug or design flaw. It is just a simple design decision.
