### ISSUE TITLE
Drop persistence support

### ISSUE THREAD

**Issue by buraksezer** [buraksezer/olric#6]
Drop persistence support. It was too early to add. BadgerDB is not suitable to fulfil our requirements. We may implement an in-house persistence support in the future. Of course, after implementing a proper fsck component.

**Comment by nadilas** [comment]
Hi, the project looks great. Do you have any current plans or are you working on storage / persistence?

**Comment by buraksezer** [comment]
@nadilas thank you very much! I have plans to build a persistence layer which can be backed by any storage system or database. Consider this:

```go
type DMapPersistence interface {
    Store(key string, value []byte) error
    Delete(key string) error
    DeleteAll() error
    Load(key string) ([]byte, error)
    LoadAll() ([]byte, error)
}
```

A plugin by any user or an internal package can implement this interface to store in-memory key/value data on any system. Please take a look at the following documents:

https://docs.hazelcast.org/docs/latest/manual/html-single/#loading-and-storing-persistent-data
https://hazelcast.com/blog/persisting-in-memory-data-for-later-usage/

By the way, do you want to use Olric in your projects? I would like to hear more about your use cases and I'm here to answer your questions about the integration.

Thanks for your interest!

**Comment by nadilas** [comment]
@buraksezer I‘m currently implementing Olric as an embedded cache layer in one of my services, where I previously had `bigcache` Inside. This service is scheduled under HA so we have multiple instances each building their own runtime cache, which obviously requires more resources than needed. We have used hazelcast before, but turns out it had too much of an overhead. Olric seems to be a good middleground.

As I see from your link, you are thinking of persistence in the hazelcast sense, which is not quite what I had in mind, but seems reasonable enough, so that I wouldn‘t have to write my own loaders when the application is starting.

One thing which I would kind of need is, and I didn‘t find a solution for out of the box is a key expired hook. Currently I‘m letting my watchers reload all the DMaps after the TTL, but this essentially means, that a huge chunk of work happens and from the expiration until the loader is complete the DMap is empty. Individual hooks could make this gap smaller and let each key reload on its own. Do you have any options for a callback/hook currently implemented?

**Comment by buraksezer** [comment]
> As I see from your link, you are thinking of persistence in the hazelcast sense, which is not quite what I had in mind, but seems reasonable enough, so that I wouldn‘t have to write my own loaders when the application is starting.

I would like to hear more about your design choice. I'm fully open to new ideas. 

> Individual hooks could make this gap smaller and let each key reload on its own. Do you have any options for a callback/hook currently implemented?

It's not implemented right now, but it's easy to implement. I have a working distributed topic implementation ([feature/issue-36](https://github.com/buraksezer/olric/blob/feature/issue-36/dtopic.go)) and it's easy to implement event listeners on top of it. I can deliver that feature in a couple of weeks.  

Some design considerations:

* Message order is not guaranteed,
* Message delivery is not guaranteed: fire and forget.
* Event notifications (via DTopic implementation) for expired cache entries may be delayed. 

We need to improve the eviction algorithm. There should be an upper limit for delays. 

By the way, I would like to learn more about setup. For example: access patterns, cluster size, average payload size and expected key count. It's great to know these things to improve Olric and its documentation in a positive manner.

**Comment by buraksezer** [comment]
Hi @nadilas, sorry for the late response.

> ... Then when the new application nodes are coming back up they can rehydrate from that storage when starting up. Really only as hybernation technique.

This is what I want to implement. I'm going to start working on this in v0.4.x or v0.5.x milestones. I'm not sure about the timing.

> Again, I don't think you really need this, but I would be interested why you decided to implement DTopic?

Olric is started as a distributed cache, but I think that it should be reinforced by implementing some useful features such as PubSub or some level of persistence. The current implementation of DTopic is quite primitive and it needs non-trivial amount of work to be stabilized. We also need a more complicated implementation to provide delivery and order guaranties. But I think the initial implementation is still good enough for event listeners. Before/After hooks (with client support) need order guarantee. 

> I'd much rather see the possibility to do queries on values, then a built-in pubsub feature. 🙏 😄

2021-2022 :)

> Sure, I can give you some of those, but maybe somewhere else? :)

Of course! You can find my email address on my GitHub account.

**Comment by bitcard** [comment]
mark
