### ISSUE TITLE
Questions about olric

### ISSUE THREAD

**Issue by frederikhors** [buraksezer/olric#79]
How is it different from https://github.com/dgraph-io/ristretto?

Are there any benchmarks with similar products?

**Comment by buraksezer** [comment]
Hi @frederikhors 

I'm so sorry for extreme delay in my response. Olric is a distributed, embeddable data structure server. It currently implements distributed map and distributed topic data structures. Because of its consistency model, Olric is useful as a distributed cache library for your Go applications. It also supports a few eviction policies including LRU. 

I have a little info about Ristretto library of DGraph. It is not distributed. So Olric is completely different and it can be comparable with [groupcache](https://github.com/golang/groupcache).

> Are there any benchmarks with similar products?

It provides sub-millisecond performance on AWS EC2 with a few cluster members and sane defaults. But I don't have any recent benchmarks. `olric-load` is useful to get some insight about the performance.

From my development host:

```
olric-load -a 192.168.1.3:3320 -s msgpack -k 1000000 -c put
### STATS FOR COMMAND: PUT ###
Serializer is msgpack
1000000 requests completed in 6.943316278s
50 parallel clients

98.36% <= 0 milliseconds
99.50% <= 1 milliseconds
99.79% <= 2 milliseconds
99.91% <= 3 milliseconds
99.95% <= 4 milliseconds
99.96% <= 5 milliseconds
99.96% <= 6 milliseconds
99.97% <= 7 milliseconds
99.98% <= 10 milliseconds
99.99% <= 15 milliseconds
100.00% <= 96 milliseconds

144023.397460 requests per second
```
